/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedStaffMonitoringRouteImport } from './routes/_authenticated/staff-monitoring'
import { Route as AuthenticatedStaffAccessRouteImport } from './routes/_authenticated/staff-access'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsGeneratorRouteImport } from './routes/_authenticated/reports-generator'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProgressHubRouteImport } from './routes/_authenticated/progress-hub'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedHolidaysRouteImport } from './routes/_authenticated/holidays'
import { Route as AuthenticatedGradebookRouteImport } from './routes/_authenticated/gradebook'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedCommunicationRouteImport } from './routes/_authenticated/communication'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedChildrenRouteImport } from './routes/_authenticated/children'
import { Route as AuthenticatedAttendanceOverviewRouteImport } from './routes/_authenticated/attendance-overview'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedChildrenIndexRouteImport } from './routes/_authenticated/children.index'
import { Route as AuthenticatedChildrenStudentIdRouteImport } from './routes/_authenticated/children.$studentId'
import { Route as AuthenticatedChildrenStudentIdIndexRouteImport } from './routes/_authenticated/children.$studentId.index'
import { Route as AuthenticatedChildrenStudentIdReportRouteImport } from './routes/_authenticated/children.$studentId.report'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffMonitoringRoute =
  AuthenticatedStaffMonitoringRouteImport.update({
    id: '/staff-monitoring',
    path: '/staff-monitoring',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffAccessRoute =
  AuthenticatedStaffAccessRouteImport.update({
    id: '/staff-access',
    path: '/staff-access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsGeneratorRoute =
  AuthenticatedReportsGeneratorRouteImport.update({
    id: '/reports-generator',
    path: '/reports-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressHubRoute =
  AuthenticatedProgressHubRouteImport.update({
    id: '/progress-hub',
    path: '/progress-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHolidaysRoute = AuthenticatedHolidaysRouteImport.update({
  id: '/holidays',
  path: '/holidays',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradebookRoute = AuthenticatedGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunicationRoute =
  AuthenticatedCommunicationRouteImport.update({
    id: '/communication',
    path: '/communication',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChildrenRoute = AuthenticatedChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceOverviewRoute =
  AuthenticatedAttendanceOverviewRouteImport.update({
    id: '/attendance-overview',
    path: '/attendance-overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChildrenIndexRoute =
  AuthenticatedChildrenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChildrenRoute,
  } as any)
const AuthenticatedChildrenStudentIdRoute =
  AuthenticatedChildrenStudentIdRouteImport.update({
    id: '/$studentId',
    path: '/$studentId',
    getParentRoute: () => AuthenticatedChildrenRoute,
  } as any)
const AuthenticatedChildrenStudentIdIndexRoute =
  AuthenticatedChildrenStudentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChildrenStudentIdRoute,
  } as any)
const AuthenticatedChildrenStudentIdReportRoute =
  AuthenticatedChildrenStudentIdReportRouteImport.update({
    id: '/report',
    path: '/report',
    getParentRoute: () => AuthenticatedChildrenStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-overview': typeof AuthenticatedAttendanceOverviewRoute
  '/children': typeof AuthenticatedChildrenRouteWithChildren
  '/classes': typeof AuthenticatedClassesRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/gradebook': typeof AuthenticatedGradebookRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/progress-hub': typeof AuthenticatedProgressHubRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reports-generator': typeof AuthenticatedReportsGeneratorRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff-access': typeof AuthenticatedStaffAccessRoute
  '/staff-monitoring': typeof AuthenticatedStaffMonitoringRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/users': typeof AuthenticatedUsersRoute
  '/children/$studentId': typeof AuthenticatedChildrenStudentIdRouteWithChildren
  '/children/': typeof AuthenticatedChildrenIndexRoute
  '/children/$studentId/report': typeof AuthenticatedChildrenStudentIdReportRoute
  '/children/$studentId/': typeof AuthenticatedChildrenStudentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/attendance-overview': typeof AuthenticatedAttendanceOverviewRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/communication': typeof AuthenticatedCommunicationRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/gradebook': typeof AuthenticatedGradebookRoute
  '/holidays': typeof AuthenticatedHolidaysRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/progress-hub': typeof AuthenticatedProgressHubRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reports-generator': typeof AuthenticatedReportsGeneratorRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff-access': typeof AuthenticatedStaffAccessRoute
  '/staff-monitoring': typeof AuthenticatedStaffMonitoringRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/users': typeof AuthenticatedUsersRoute
  '/children': typeof AuthenticatedChildrenIndexRoute
  '/children/$studentId/report': typeof AuthenticatedChildrenStudentIdReportRoute
  '/children/$studentId': typeof AuthenticatedChildrenStudentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/attendance-overview': typeof AuthenticatedAttendanceOverviewRoute
  '/_authenticated/children': typeof AuthenticatedChildrenRouteWithChildren
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/communication': typeof AuthenticatedCommunicationRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/gradebook': typeof AuthenticatedGradebookRoute
  '/_authenticated/holidays': typeof AuthenticatedHolidaysRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/progress-hub': typeof AuthenticatedProgressHubRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reports-generator': typeof AuthenticatedReportsGeneratorRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff-access': typeof AuthenticatedStaffAccessRoute
  '/_authenticated/staff-monitoring': typeof AuthenticatedStaffMonitoringRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/children/$studentId': typeof AuthenticatedChildrenStudentIdRouteWithChildren
  '/_authenticated/children/': typeof AuthenticatedChildrenIndexRoute
  '/_authenticated/children/$studentId/report': typeof AuthenticatedChildrenStudentIdReportRoute
  '/_authenticated/children/$studentId/': typeof AuthenticatedChildrenStudentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/announcements'
    | '/assets'
    | '/assignments'
    | '/attendance'
    | '/attendance-overview'
    | '/children'
    | '/classes'
    | '/communication'
    | '/complaints'
    | '/dashboard'
    | '/fees'
    | '/fleet'
    | '/gradebook'
    | '/holidays'
    | '/library'
    | '/payments'
    | '/progress-hub'
    | '/reports'
    | '/reports-generator'
    | '/settings'
    | '/staff-access'
    | '/staff-monitoring'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/users'
    | '/children/$studentId'
    | '/children/'
    | '/children/$studentId/report'
    | '/children/$studentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/announcements'
    | '/assets'
    | '/assignments'
    | '/attendance'
    | '/attendance-overview'
    | '/classes'
    | '/communication'
    | '/complaints'
    | '/dashboard'
    | '/fees'
    | '/fleet'
    | '/gradebook'
    | '/holidays'
    | '/library'
    | '/payments'
    | '/progress-hub'
    | '/reports'
    | '/reports-generator'
    | '/settings'
    | '/staff-access'
    | '/staff-monitoring'
    | '/students'
    | '/teachers'
    | '/timetable'
    | '/users'
    | '/children'
    | '/children/$studentId/report'
    | '/children/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/announcements'
    | '/_authenticated/assets'
    | '/_authenticated/assignments'
    | '/_authenticated/attendance'
    | '/_authenticated/attendance-overview'
    | '/_authenticated/children'
    | '/_authenticated/classes'
    | '/_authenticated/communication'
    | '/_authenticated/complaints'
    | '/_authenticated/dashboard'
    | '/_authenticated/fees'
    | '/_authenticated/fleet'
    | '/_authenticated/gradebook'
    | '/_authenticated/holidays'
    | '/_authenticated/library'
    | '/_authenticated/payments'
    | '/_authenticated/progress-hub'
    | '/_authenticated/reports'
    | '/_authenticated/reports-generator'
    | '/_authenticated/settings'
    | '/_authenticated/staff-access'
    | '/_authenticated/staff-monitoring'
    | '/_authenticated/students'
    | '/_authenticated/teachers'
    | '/_authenticated/timetable'
    | '/_authenticated/users'
    | '/_authenticated/children/$studentId'
    | '/_authenticated/children/'
    | '/_authenticated/children/$studentId/report'
    | '/_authenticated/children/$studentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-monitoring': {
      id: '/_authenticated/staff-monitoring'
      path: '/staff-monitoring'
      fullPath: '/staff-monitoring'
      preLoaderRoute: typeof AuthenticatedStaffMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff-access': {
      id: '/_authenticated/staff-access'
      path: '/staff-access'
      fullPath: '/staff-access'
      preLoaderRoute: typeof AuthenticatedStaffAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports-generator': {
      id: '/_authenticated/reports-generator'
      path: '/reports-generator'
      fullPath: '/reports-generator'
      preLoaderRoute: typeof AuthenticatedReportsGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress-hub': {
      id: '/_authenticated/progress-hub'
      path: '/progress-hub'
      fullPath: '/progress-hub'
      preLoaderRoute: typeof AuthenticatedProgressHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/holidays': {
      id: '/_authenticated/holidays'
      path: '/holidays'
      fullPath: '/holidays'
      preLoaderRoute: typeof AuthenticatedHolidaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradebook': {
      id: '/_authenticated/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof AuthenticatedGradebookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/communication': {
      id: '/_authenticated/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof AuthenticatedCommunicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children': {
      id: '/_authenticated/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof AuthenticatedChildrenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance-overview': {
      id: '/_authenticated/attendance-overview'
      path: '/attendance-overview'
      fullPath: '/attendance-overview'
      preLoaderRoute: typeof AuthenticatedAttendanceOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/children/': {
      id: '/_authenticated/children/'
      path: '/'
      fullPath: '/children/'
      preLoaderRoute: typeof AuthenticatedChildrenIndexRouteImport
      parentRoute: typeof AuthenticatedChildrenRoute
    }
    '/_authenticated/children/$studentId': {
      id: '/_authenticated/children/$studentId'
      path: '/$studentId'
      fullPath: '/children/$studentId'
      preLoaderRoute: typeof AuthenticatedChildrenStudentIdRouteImport
      parentRoute: typeof AuthenticatedChildrenRoute
    }
    '/_authenticated/children/$studentId/': {
      id: '/_authenticated/children/$studentId/'
      path: '/'
      fullPath: '/children/$studentId/'
      preLoaderRoute: typeof AuthenticatedChildrenStudentIdIndexRouteImport
      parentRoute: typeof AuthenticatedChildrenStudentIdRoute
    }
    '/_authenticated/children/$studentId/report': {
      id: '/_authenticated/children/$studentId/report'
      path: '/report'
      fullPath: '/children/$studentId/report'
      preLoaderRoute: typeof AuthenticatedChildrenStudentIdReportRouteImport
      parentRoute: typeof AuthenticatedChildrenStudentIdRoute
    }
  }
}

interface AuthenticatedChildrenStudentIdRouteChildren {
  AuthenticatedChildrenStudentIdReportRoute: typeof AuthenticatedChildrenStudentIdReportRoute
  AuthenticatedChildrenStudentIdIndexRoute: typeof AuthenticatedChildrenStudentIdIndexRoute
}

const AuthenticatedChildrenStudentIdRouteChildren: AuthenticatedChildrenStudentIdRouteChildren =
  {
    AuthenticatedChildrenStudentIdReportRoute:
      AuthenticatedChildrenStudentIdReportRoute,
    AuthenticatedChildrenStudentIdIndexRoute:
      AuthenticatedChildrenStudentIdIndexRoute,
  }

const AuthenticatedChildrenStudentIdRouteWithChildren =
  AuthenticatedChildrenStudentIdRoute._addFileChildren(
    AuthenticatedChildrenStudentIdRouteChildren,
  )

interface AuthenticatedChildrenRouteChildren {
  AuthenticatedChildrenStudentIdRoute: typeof AuthenticatedChildrenStudentIdRouteWithChildren
  AuthenticatedChildrenIndexRoute: typeof AuthenticatedChildrenIndexRoute
}

const AuthenticatedChildrenRouteChildren: AuthenticatedChildrenRouteChildren = {
  AuthenticatedChildrenStudentIdRoute:
    AuthenticatedChildrenStudentIdRouteWithChildren,
  AuthenticatedChildrenIndexRoute: AuthenticatedChildrenIndexRoute,
}

const AuthenticatedChildrenRouteWithChildren =
  AuthenticatedChildrenRoute._addFileChildren(
    AuthenticatedChildrenRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAttendanceOverviewRoute: typeof AuthenticatedAttendanceOverviewRoute
  AuthenticatedChildrenRoute: typeof AuthenticatedChildrenRouteWithChildren
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedCommunicationRoute: typeof AuthenticatedCommunicationRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedGradebookRoute: typeof AuthenticatedGradebookRoute
  AuthenticatedHolidaysRoute: typeof AuthenticatedHolidaysRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProgressHubRoute: typeof AuthenticatedProgressHubRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReportsGeneratorRoute: typeof AuthenticatedReportsGeneratorRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffAccessRoute: typeof AuthenticatedStaffAccessRoute
  AuthenticatedStaffMonitoringRoute: typeof AuthenticatedStaffMonitoringRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAttendanceOverviewRoute: AuthenticatedAttendanceOverviewRoute,
  AuthenticatedChildrenRoute: AuthenticatedChildrenRouteWithChildren,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedCommunicationRoute: AuthenticatedCommunicationRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedGradebookRoute: AuthenticatedGradebookRoute,
  AuthenticatedHolidaysRoute: AuthenticatedHolidaysRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProgressHubRoute: AuthenticatedProgressHubRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReportsGeneratorRoute: AuthenticatedReportsGeneratorRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffAccessRoute: AuthenticatedStaffAccessRoute,
  AuthenticatedStaffMonitoringRoute: AuthenticatedStaffMonitoringRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
